# Generated by Django 6.0 on 2025-12-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yangilik_rasmi', models.ImageField(upload_to='')),
                ('yangilik_nomi', models.CharField(max_length=500)),
                ('yangilik_xaqida', models.TextField(max_length=100000)),
            ],
        ),
    ]
