# Generated by Django 6.0 on 2025-12-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangiliklar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='yangiliklar',
            name='yangilik_rasmi',
            field=models.ImageField(upload_to='yangiliklar/'),
        ),
        migrations.AlterField(
            model_name='yangiliklar',
            name='yangilik_xaqida',
            field=models.TextField(),
        ),
    ]
