# Generated by Django 6.0 on 2025-12-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_yangiliklar_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yangiliklar',
            name='is_active',
        ),
    ]
