# Generated by Django 6.0 on 2025-12-28 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_yangiliklar_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangiliklar',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='yangilik_nomi_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='yangilik_nomi_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='yangilik_nomi_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='yangilik_xaqida_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='yangilik_xaqida_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='yangilik_xaqida_uz',
            field=models.TextField(null=True),
        ),
    ]
