# Generated by Django 6.0 on 2025-12-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_yangiliklar_created_at_yangiliklar_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLavhalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=500, verbose_name="Video nomi (O'zbekcha)")),
                ('title_uz_uz', models.CharField(max_length=500, null=True, verbose_name="Video nomi (O'zbekcha)")),
                ('title_uz_ru', models.CharField(max_length=500, null=True, verbose_name="Video nomi (O'zbekcha)")),
                ('title_uz_en', models.CharField(max_length=500, null=True, verbose_name="Video nomi (O'zbekcha)")),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='Video nomi (Ruscha)')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='Video nomi (Inglizcha)')),
                ('description_uz', models.TextField(blank=True, verbose_name="Video tavsifi (O'zbekcha)")),
                ('description_uz_uz', models.TextField(blank=True, null=True, verbose_name="Video tavsifi (O'zbekcha)")),
                ('description_uz_ru', models.TextField(blank=True, null=True, verbose_name="Video tavsifi (O'zbekcha)")),
                ('description_uz_en', models.TextField(blank=True, null=True, verbose_name="Video tavsifi (O'zbekcha)")),
                ('description_ru', models.TextField(blank=True, verbose_name='Video tavsifi (Ruscha)')),
                ('description_en', models.TextField(blank=True, verbose_name='Video tavsifi (Inglizcha)')),
                ('youtube_id', models.CharField(max_length=100, verbose_name='YouTube Video ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='Video rasmi')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='Video davomiyligi')),
                ('views_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('likes_count', models.IntegerField(default=0, verbose_name='Layklar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video Lavhalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
